# Generated by Django 3.1.7 on 2021-05-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lab', '0002_auto_20210321_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='promisiunematerial',
            name='nume',
        ),
        migrations.AddField(
            model_name='institutie',
            name='latitudine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='institutie',
            name='logitudine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sofer',
            name='disponibil',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='promisiunematerial',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Istoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cerere', models.DateTimeField()),
                ('data_plecare_sofer', models.DateTimeField()),
                ('data_livrare', models.DateTimeField()),
                ('cantitate', models.IntegerField(default=0)),
                ('institutie_donatoare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donator', to='ip_lab.institutie')),
                ('institutie_primitoare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primitor', to='ip_lab.institutie')),
                ('sofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.sofer')),
                ('tip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.tipmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Cerere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cerere', models.DateTimeField()),
                ('data_limita', models.DateTimeField()),
                ('cantitate', models.IntegerField(default=0)),
                ('prioritate', models.IntegerField(default=0)),
                ('institutie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.institutie')),
                ('tip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.tipmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip_material', to='ip_lab.tipmaterial'),
        ),
        migrations.AddField(
            model_name='promisiunematerial',
            name='tip_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.tipmaterial'),
        ),
    ]
