# Generated by Django 3.1.7 on 2021-05-16 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGuvern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institutie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=500)),
                ('logitudine', models.FloatField(default=0)),
                ('latitudine', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_start', models.IntegerField(default=0)),
                ('ora_sfarsit', models.IntegerField(default=0)),
                ('disponibil', models.BooleanField(default=False, null=True)),
                ('institutie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soferi', to='ip_lab.institutie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromisiuneMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitati', models.IntegerField(default=0)),
                ('data', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='ip_lab.agentguvern')),
                ('institutie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promisiune', to='ip_lab.institutie')),
                ('tip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.tipmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitati', models.IntegerField(default=0)),
                ('surplus', models.BooleanField(default=False, null=True)),
                ('institutie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiale', to='ip_lab.institutie')),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip_material', to='ip_lab.tipmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Istoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cerere', models.DateTimeField()),
                ('data_plecare_sofer', models.DateTimeField()),
                ('data_livrare', models.DateTimeField()),
                ('cantitate', models.IntegerField(default=0)),
                ('institutie_donatoare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donator', to='ip_lab.institutie')),
                ('institutie_primitoare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primitor', to='ip_lab.institutie')),
                ('sofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.sofer')),
                ('tip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.tipmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Cerere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cerere', models.DateTimeField()),
                ('data_limita', models.DateTimeField()),
                ('cantitate', models.IntegerField(default=0)),
                ('prioritate', models.IntegerField(default=0)),
                ('institutie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.institutie')),
                ('tip_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_lab.tipmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administratori', to='ip_lab.institutie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
